In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Data_for_UCI_named.csv')

In [3]:
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4      stab     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable

In [4]:
df.shape

(10000, 14)

In [5]:
df = df.drop(columns = ['stab'])

In [6]:
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4     stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1 -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4 -0.554305  0.797110  0.455450  0.656947  0.820923  unstable

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 13 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   tau1    10000 non-null  float64
 1   tau2    10000 non-null  float64
 2   tau3    10000 non-null  float64
 3   tau4    10000 non-null  float64
 4   p1      10000 non-null  float64
 5   p2      10000 non-null  float64
 6   p3      10000 non-null  float64
 7   p4      10000 non-null  float64
 8   g1      10000 non-null  float64
 9   g2      10000 non-null  float64
 10  g3      10000 non-null  float64
 11  g4      10000 non-null  float64
 12  stabf   10000 non-null  object 
dtypes: float64(12), object(1)
memory usage: 1015.8+ KB


In [8]:
#encode categorical feature

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['stabf'] = le.fit_transform(df['stabf'])

In [9]:
df.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4  stabf  
0 -1.723086  0.650456  0.859578  0.887445  0.958034      1  
1 -1.255012  0.413441  0.862414  0.562139  0.781760      0  
2 -0.920492  0.163041  0.766689  0.839444  0.109853      1  
3 -0.997374  0.446209  0.976744  0.929381  0.362718      1  
4 -0.554305  0.797110  0.455450  0.656947  0.820923      1

In [10]:
df.shape

(10000, 13)

In [11]:
df['stabf'].value_counts()

1    6380
0    3620
Name: stabf, dtype: int64

In [12]:
# feature scalling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaled_features = scaler.fit_transform(df.drop('stabf', axis = 1))
df_feat = pd.DataFrame(scaled_features,columns=df.columns[:12])

In [13]:
df_feat

tau1      tau2      tau3      tau4        p1        p2        p3  \
0    -0.835374 -0.791317  1.141704  1.652103  0.017397  1.079405 -0.017078   
1     1.478297 -0.126705 -0.803111 -1.415043  1.752124 -1.593619 -1.438158   
2     1.357093  1.312140 -0.803499 -1.471504 -0.458492  0.098253 -0.062840   
3    -1.653138  0.882289 -0.278354 -1.060901  0.284250  0.513904 -1.591046   
4    -0.771543  0.860108 -0.111670  1.680114 -0.298075  0.287450 -1.376343   
...        ...       ...       ...       ...       ...       ...       ...   
9995 -0.845823  1.545219 -1.047793  0.341961 -0.540582  1.367041 -0.459815   
9996 -0.677397 -1.449518 -0.836875  0.599749  0.797094 -0.955307  0.687190   
9997 -1.052346 -0.878049  1.285871 -1.546478  0.731231 -0.301880  0.706942   
9998  1.597686 -0.457846 -0.909029  0.937621 -1.642346  0.655109  1.385835   
9999  0.466935  0.558555 -0.328291  1.248220 -0.341956 -0.323974 -0.651695   

            p4        g1        g2        g3        g4  
0    -1.092545  0.457467  1.220013  1.321628  1.579026  
1    -0.011575 -0.406791  1.230354  0.135424  0.936256  
2     0.760963 -1.319852  0.881299  1.146596 -1.513802  
3     0.583414 -0.287304  1.647250  1.474543 -0.591750  
4     1.606636  0.992226 -0.253610  0.481133  1.079063  
...        ...       ...       ...       ...       ...  
9995  0.031739  0.279714  0.928533  1.052035  0.304055  
9996 -1.116396 -0.083579  0.154031 -0.871936 -0.579344  
9997 -1.675175 -0.135508  1.682844 -1.370013 -1.382054  
9998  0.811729 -0.582529  0.228110  1.327730  1.069829  
9999  1.569629 -1.647977 -0.071321 -0.533251  1.522860  

[10000 rows x 12 columns]

## Model buliding

In [14]:
X = df_feat.values
y = df['stabf'].values

In [15]:
X

array([[-0.83537431, -0.79131661,  1.14170354, ...,  1.22001311,
         1.32162751,  1.57902607],
       [ 1.47829663, -0.12670487, -0.80311147, ...,  1.23035426,
         0.13542358,  0.93625569],
       [ 1.35709296,  1.31213982, -0.80349871, ...,  0.88129868,
         1.14659574, -1.51380226],
       ...,
       [-1.05234609, -0.87804866,  1.28587062, ...,  1.68284371,
        -1.37001303, -1.38205402],
       [ 1.59768553, -0.45784646, -0.90902909, ...,  0.2281105 ,
         1.32772953,  1.06982944],
       [ 0.4669346 ,  0.55855544, -0.32829064, ..., -0.0713212 ,
        -0.53325125,  1.52285961]])

In [16]:
y

array([1, 0, 1, ..., 0, 1, 1])

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.2, random_state = 1)

In [18]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 12)
(2000, 12)
(8000,)
(2000,)


In [19]:
import imblearn
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state= 1 )
X_train_balanced, y_balanced = smote.fit_resample(X_train, y_train)

In [20]:
from collections import Counter
print('Before Smote:', Counter(y_train))
print('After Smote:', Counter(y_balanced))

Before Smote: Counter({1: 5092, 0: 2908})
After Smote: Counter({1: 5092, 0: 5092})


In [21]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt.fit(X_train_balanced,y_balanced)

DecisionTreeClassifier()

In [22]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()
rf.fit(X_train_balanced,y_balanced)

RandomForestClassifier()

In [23]:
ypred_test = rf.predict(X_test)
ypred_train = rf.predict(X_train)

In [24]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
from sklearn.metrics import classification_report

# prediction on test data

y_pred_test = rf.predict(X_test)

#Actual value : ytest
#prediction : y_pred_test
print(confusion_matrix(y_test,y_pred_test ))

# classification report
print('Accuracy: %.4f' % accuracy_score(y_test, y_pred_test))


[[ 641   71]
 [  95 1193]]
Accuracy: 0.9170


In [25]:
!pip install XgBoost

In [26]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train_balanced,y_balanced)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [33]:
# prediction on test data

y_pred_test = xgb.predict(X_test)

#Actual value : ytest
#prediction : y_pred_test
print(confusion_matrix(y_test,y_pred_test ))

# classification report
print('Accuracy: %.4f' % accuracy_score(y_test, y_pred_test))


[[ 664   48]
 [  67 1221]]
Accuracy: 0.9425


In [30]:
!pip install lightgbm

In [31]:
import lightgbm as lgb
from lightgbm import LGBMClassifier
clf = lgb.LGBMClassifier()
clf.fit(X_train_balanced,y_balanced)

LGBMClassifier()

In [32]:
# prediction on test data

y_pred_test = clf.predict(X_test)

#Actual value : ytest
#prediction : y_pred_test
print(confusion_matrix(y_test,y_pred_test ))

# classification report
print('Accuracy: %.4f' % accuracy_score(y_test, y_pred_test))


[[ 672   40]
 [  83 1205]]
Accuracy: 0.9385


In [41]:
from sklearn.ensemble import ExtraTreesClassifier
etc = ExtraTreesClassifier(cv=5, n_iter=10, scoring = 'accuracy', n_jobs = -1, verbose = 1, random_state = 1)
etc.fit(X_train_balanced,y_balanced)

TypeError: __init__() got an unexpected keyword argument 'n_iter'